In [2]:
import pandas as pd
df = pd.read_excel("Movies_Dataset.xlsx") 
df

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [3]:
df.columns

Index(['Movie Name', 'Genre', 'Release_Year', 'IMDb_Rating', 'Revenue'], dtype='str')

In [5]:
# 1.Select all movies in the "Action" genre. 
df[df.Genre == "Action"]['Movie Name']

4        Movie 5
34      Movie 35
64      Movie 65
65      Movie 66
73      Movie 74
         ...
930    Movie 931
944    Movie 945
980    Movie 981
988    Movie 989
998    Movie 999
Name: Movie Name, Length: 104, dtype: str

In [13]:
df.dtypes

Movie Name          str
Genre               str
Release_Year      int64
IMDb_Rating     float64
Revenue         float64
dtype: object

In [15]:
# 2. Select movies released after 2000. 
df.loc[df['Release_Year'] > 2000, 'Movie Name']

2        Movie 3
3        Movie 4
4        Movie 5
6        Movie 7
7        Movie 8
         ...
988    Movie 989
989    Movie 990
991    Movie 992
995    Movie 996
997    Movie 998
Name: Movie Name, Length: 518, dtype: str

In [17]:

# 3. Select movies with an IMDb rating greater than 8.5.
df[df.IMDb_Rating > 8.5]

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
34     Movie 35     Action          2009          8.7   545.60
51     Movie 52    Mystery          1998          9.0  1089.93
56     Movie 57     Comedy          1993          9.2  1586.13
74     Movie 75  Adventure          1999          8.6  1688.49
81     Movie 82    Mystery          1997          8.6  1238.32
..          ...        ...           ...          ...      ...
991   Movie 992   Thriller          2004          9.2   251.25
992   Movie 993     Horror          1985          9.6   951.23
995   Movie 996     Sci-Fi          2013          8.7   456.39
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[148 rows x 5 columns]

In [20]:
# 4. Select only "Movie Name" and "Genre" columns. 
df[["Movie Name","Genre"]]

     Movie Name      Genre
0       Movie 1     Sci-Fi
1       Movie 2  Adventure
2       Movie 3    Romance
3       Movie 4    Romance
4       Movie 5     Action
..          ...        ...
995   Movie 996     Sci-Fi
996   Movie 997  Adventure
997   Movie 998    Fantasy
998   Movie 999     Action
999  Movie 1000     Horror

[1000 rows x 2 columns]

In [36]:
# 5. Select movies released between 1990 and 2010.
df.loc[(df['Release_Year'] >= 1990) & (df['Release_Year'] <= 2010), 'Movie Name']    
# df[(df.Release_Year >= 1990) |  (df.Release_Year <= 2010)]

0         Movie 1
1         Movie 2
2         Movie 3
3         Movie 4
5         Movie 6
          ...
991     Movie 992
994     Movie 995
996     Movie 997
998     Movie 999
999    Movie 1000
Name: Movie Name, Length: 500, dtype: str

In [43]:
# 6.Count the number of movies in each genre. 
print(df.Genre.value_counts())

Genre
Drama        113
Comedy       110
Fantasy      107
Thriller     107
Action       104
Adventure     96
Sci-Fi        93
Romance       91
Horror        90
Mystery       89
Name: count, dtype: int64

In [62]:
# 7. Find the highest IMDb-rated movie. 
# df.loc[df['IMDb_Rating'].idxmax(), ['Movie Name', 'IMDb_Rating']]
df.loc[df.IMDb_Rating.idxmax(), ['Movie Name','IMDb_Rating']] # (or) df.loc[df[IMDb_Rating]idxmax(), ['Movie Name','IMDb_Rating']]

Movie Name     Movie 107
IMDb_Rating         10.0
Name: 106, dtype: object

In [66]:
# 8. Find the average IMDb rating of all movies. 
df['IMDb_Rating'].mean() # df.IMDb_Rating.mean()

np.float64(5.458600000000001)

In [68]:
# 9. Find the total box office collection of all movies. 
print(df.Revenue.sum())

1049716.26

In [69]:
# 10. Select movies with box office earnings greater than 500 million. 
df[df['Revenue'] > 500]['Movie Name']

0         Movie 1
1         Movie 2
2         Movie 3
3         Movie 4
4         Movie 5
          ...
993     Movie 994
996     Movie 997
997     Movie 998
998     Movie 999
999    Movie 1000
Name: Movie Name, Length: 774, dtype: str